samples_tsv:

fastq_ext: ".fastq.gz"

paired_end:
  activate: True
  tags: [".bam_R1", ".bam_R2"]

merge_fastq:
  activate: False
  tags:

ref:
  species: "mus_musculus"
  assembly: "GRCm39"
  ensembl_release: 104

trim:
  phred_qual: 20
  length: 35
  extra: ""

align:
  read_length: 50
  extra: ""

count:
  min_qual: 1
  strandedness: 0
  min_overlap: 35
  frac_overlap: 0.9
  extra: ""