---
title: "Differential Gene Expression Analysis"
subtitle: "211001_APOE_Mm dataset"
author: "Lachlan Baer"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    fig_width: 8
    fig_height: 6
    fig_align: "center"
    code_folding: hide
editor_options:
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  error = FALSE,
  fig.align = "center"
)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

# Poster plots

```{r}
tt <- topTables_chosen$APOE2v3_male
man <- tt %>%
  mutate(mid = (start + end) / 2) %>%
  dplyr::select(gene_id, gene_name, chromosome, mid, FDR) %>%
  dplyr::filter(!(chromosome %in% c("X", "Y", "MT"))) %>%
  group_by(chromosome) %>%
  summarise(chrLen = max(mid)) %>%
  mutate(chrSt = cumsum(chrLen)-chrLen) %>%
  dplyr::select(-chrLen) %>% 
  left_join(tt) %>%
  mutate(mid = (start + end) / 2) %>%
  mutate(midCum = chrSt + mid) %>%
  mutate(
    colour = ifelse(chromosome %in% primary_chrs[c(TRUE, FALSE)], "a", "b"),
    colour = ifelse(chromosome == "7", "c", colour)
  ) %>%
  mutate(DE = FDR < 0.05)
axis <- man %>%
  group_by(chromosome) %>%
  summarise(center = (max(midCum) + min(midCum)) / 2)
ggplot(man, aes(x = midCum, y = -log10(PValue))) +
  geom_point(
    data = man %>%
      dplyr::filter(!DE),
    aes(colour = colour),
    shape = 20,
    alpha = 1,
    size = 1
  ) +
  scale_colour_manual(values = c("grey50", "grey80", "red")) +
  geom_point(
    data = man %>%
      dplyr::filter(DE),
    aes(fill = colour),
    colour = "black",
    shape = 23,
    alpha = 1,
    size = 1,
    stroke = 0.3
  ) +
  geom_hline(yintercept = -log10(0.0021775), linetype = "dashed", colour = "black") +
  scale_fill_manual(values = c("grey50", "grey80", "red")) +
  scale_x_continuous(label = axis$chromosome, breaks = axis$center) +
  scale_y_continuous(expand = c(0, 0)) +
  coord_cartesian(clip = "off") +
  labs(
    x = "Chromosome",
    y = expression(paste(-log[10], "(p)"))
  ) +
  theme(
    legend.position="none",
    panel.border = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.text = element_text(size = rel(0.8)),
    axis.title = element_text(size = rel(0.8))
  )
```

```{r}
ggsave(
  "~/phd/conferences/ABACBS2022/man_plot.png",
  device = "png",
  width = 18,
  height = 12,
  units = "cm"
)
```

